### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by kbarbary** [bccp/website#2]
## Content:
- [ ] Fix markup on research page; 
- [x] get images into in `images/` directory.
- [x] Fix markup on inidividual people pages.
- [ ] Graphics on front page
- [ ] text on front page
## Discussion items:
- What message do we want to give people after visiting the site?
- Theme. Feel of the site; in words? Hip, serious, laid-back, academia, Landau, Feymann?
- Color scheme; font; developing around the theme words.
- News / Public out-reach? Do we want a blog / twitter channel? Do we have the capability to operate it?
